//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var tree_ttypes = require('./tree_types')
var root_ttypes = require('./root_types')
var nodetypemanager_ttypes = require('./nodetypemanager_types')


var ttypes = module.exports = {};
