//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var tree_ttypes = require('./tree_types')


var ttypes = module.exports = {};
if (typeof API === 'undefined') {
  API = {};
}
