//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var tree_ttypes = require('./tree_types')


var ttypes = require('./root_types');
//HELPER FUNCTIONS AND STRUCTURES

TRootService_getTree_args = function(args) {
  this.path = null;
  if (args) {
    if (args.path !== undefined) {
      this.path = args.path;
    }
  }
};
TRootService_getTree_args.prototype = {};
TRootService_getTree_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.path = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TRootService_getTree_args.prototype.write = function(output) {
  output.writeStructBegin('TRootService_getTree_args');
  if (this.path !== null && this.path !== undefined) {
    output.writeFieldBegin('path', Thrift.Type.STRING, 1);
    output.writeString(this.path);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TRootService_getTree_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
TRootService_getTree_result.prototype = {};
TRootService_getTree_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new tree_ttypes.TTree();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TRootService_getTree_result.prototype.write = function(output) {
  output.writeStructBegin('TRootService_getTree_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TRootService_move_args = function(args) {
  this.sourcePath = null;
  this.destPath = null;
  if (args) {
    if (args.sourcePath !== undefined) {
      this.sourcePath = args.sourcePath;
    }
    if (args.destPath !== undefined) {
      this.destPath = args.destPath;
    }
  }
};
TRootService_move_args.prototype = {};
TRootService_move_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.sourcePath = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.destPath = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TRootService_move_args.prototype.write = function(output) {
  output.writeStructBegin('TRootService_move_args');
  if (this.sourcePath !== null && this.sourcePath !== undefined) {
    output.writeFieldBegin('sourcePath', Thrift.Type.STRING, 1);
    output.writeString(this.sourcePath);
    output.writeFieldEnd();
  }
  if (this.destPath !== null && this.destPath !== undefined) {
    output.writeFieldBegin('destPath', Thrift.Type.STRING, 2);
    output.writeString(this.destPath);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TRootService_move_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
TRootService_move_result.prototype = {};
TRootService_move_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.BOOL) {
        this.success = input.readBool();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

TRootService_move_result.prototype.write = function(output) {
  output.writeStructBegin('TRootService_move_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.BOOL, 0);
    output.writeBool(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

TRootServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
TRootServiceClient.prototype = {};
TRootServiceClient.prototype.seqid = function() { return this._seqid; }
TRootServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
TRootServiceClient.prototype.getTree = function(path, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getTree(path);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getTree(path);
  }
};

TRootServiceClient.prototype.send_getTree = function(path) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getTree', Thrift.MessageType.CALL, this.seqid());
  var args = new TRootService_getTree_args();
  args.path = path;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TRootServiceClient.prototype.recv_getTree = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TRootService_getTree_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getTree failed: unknown result');
};
TRootServiceClient.prototype.move = function(sourcePath, destPath, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_move(sourcePath, destPath);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_move(sourcePath, destPath);
  }
};

TRootServiceClient.prototype.send_move = function(sourcePath, destPath) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('move', Thrift.MessageType.CALL, this.seqid());
  var args = new TRootService_move_args();
  args.sourcePath = sourcePath;
  args.destPath = destPath;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

TRootServiceClient.prototype.recv_move = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new TRootService_move_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('move failed: unknown result');
};
TRootServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
TRootServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

TRootServiceProcessor.prototype.process_getTree = function(seqid, input, output) {
  var args = new TRootService_getTree_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getTree.length === 1) {
    Q.fcall(this._handler.getTree, args.path)
      .then(function(result) {
        var result = new TRootService_getTree_result({success: result});
        output.writeMessageBegin("getTree", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new TRootService_getTree_result(err);
        output.writeMessageBegin("getTree", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getTree(args.path,  function (err, result) {
      var result = new TRootService_getTree_result((err != null ? err : {success: result}));
      output.writeMessageBegin("getTree", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

TRootServiceProcessor.prototype.process_move = function(seqid, input, output) {
  var args = new TRootService_move_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.move.length === 2) {
    Q.fcall(this._handler.move, args.sourcePath, args.destPath)
      .then(function(result) {
        var result = new TRootService_move_result({success: result});
        output.writeMessageBegin("move", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new TRootService_move_result(err);
        output.writeMessageBegin("move", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.move(args.sourcePath, args.destPath,  function (err, result) {
      var result = new TRootService_move_result((err != null ? err : {success: result}));
      output.writeMessageBegin("move", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

